version: '3.1'

services:
  frontend:
    build:
      context: ./Frontend/inventory_management_system
      dockerfile: Dockerfile
    container_name: frontend-app
    ports:
      - 80:80
    environment:
      - REACT_APP_BACKEND_BASE_URL=localhost
      - REACT_APP_BACKEND_PORT=4000
    depends_on:
      - backend
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend-app
    ports:
      - 4000:4000
    environment:
      - PORT=4000
      - mongoURI=${MONGO_URI}
  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok-tunnel
    command: ["http", "frontend-app:80"]
    environment:
      NGROK_AUTHTOKEN: "${NGROK_AUTHTOKEN}"
    ports:
      - 4040:4040
    # depends_on:
    #   - frontend
    