version: '3.1'

services:
  frontend:
    build:
      context: ./Frontend/inventory_management_system
      dockerfile: Dockerfile
    container_name: frontend-app
    ports:
      - 80:80
    environment:
      - REACT_APP_BACKEND_BASE_URL=localhost
      - REACT_APP_BACKEND_PORT=4000
    depends_on:
      - backend
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend-app
    ports:
      - 4000:4000
    environment:
      - PORT=4000
      - mongoURI=mongodb+srv://docker:iLnyNdk1a307cljn@myatlasclusteredu.majd3mj.mongodb.net/?retryWrites=true&w=majority&appName=myAtlasClusterEDU
    