name: Build and Deploy on Computesphere

on:
  workflow_dispatch:
  push:
    branches:
      - testing
      - main

jobs:
  # build-deploy-backend:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Build Image
  #     uses: computesphere/build-and-deploy-image-action@v1
  #     with:
  #       mode: build-and-deploy
  #       name: ${{ vars.IMAGE_NAME }}/backend-mern:v.${{ github.run_number }}
  #       account_id: ${{ vars.COMPUTESPHERE_ACCOUNT_ID }}
  #       token: ${{ secrets.COMPUTESPHERE_API_TOKEN }}
  #       deployment_id: ${{ vars.DEPLOYMENT_ID }}
  #       registry: ${{ vars.REGISTRY }}
  #       type: private
  #       username: ${{ secrets.DOCKERHUB_USERNAME }}
  #       password: ${{ secrets.DOCKERHUB_TOKEN }}
  #       dockerfile: ./Backend/Dockerfile detect-changes
 
  check-changed-directory:
    name: Test changed-files
    uses: chukwukelu2023/automation-hub/.github/workflows/detect-file-change.yaml@detect-changes
    # outputs:
    #   changed_dir: ${{ jobs.check-changed-directory.outputs.check-changes }}

  use-files:
    runs-on: ubuntu-latest
    needs: check-changed-directory
    steps:
      - name: Use changed files
        run: |
          echo "Detected changes:"
          echo "${{ needs.check-changed-directory.outputs.check-changes }}"

  # build_and_push_backend:
  #   uses: chukwukelu2023/automation-hub/.github/workflows/image_build_dockerhub.yaml@v1.0.0
  #   with:
  #     context-path: ./Backend
  #     tag-name: oluchioraekwe/backend-mern:v.${{ github.run_number }}
  #     registry-name: docker.io
  #   secrets:
  #      REGISTRY-PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
  #      REGISTRY-USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
