name: Build and Deploy MERN APP

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging
      trigger-backend:
        description: 'Trigger backend build'
        required: false
        default: 'no_build'
        type: choice
        options:
          - no_build
          - build
      trigger-frontend:
        description: 'Trigger frontend build'
        required: false
        default: 'no_build'
        type: choice
        options:
          - no_build
          - build
  push:
    branches:
      - testing
      - staging
      - main

jobs:
  check-changed-directory:
    name: Test changed-files
    uses: chukwukelu2023/automation-hub/.github/workflows/detect-file-change.yaml@detect-changes 

  check-files:
    runs-on: ubuntu-latest
    needs: check-changed-directory
    steps:
      - name: Changed files
        run: |
          echo "Detected changes: "
          echo "${{ needs.check-changed-directory.outputs.check-changes }}"

  
  build-deploy-backend:
    runs-on: ubuntu-latest
    needs: check-changed-directory
    if: contains(needs.check-changed-directory.outputs.check-changes, 'Backend/') || inputs.trigger-backend == 'build'
    steps:
    - uses: actions/checkout@v4
    - name: Build Image
      uses: computesphere/build-and-deploy-image-action@v1
      with:
        mode: build-and-deploy
        name: ${{ vars.IMAGE_NAME }}/backend-mern:v.0.${{ github.run_number }}
        account_id: ${{ vars.COMPUTESPHERE_ACCOUNT_ID }}
        token: ${{ secrets.COMPUTESPHERE_API_TOKEN }}
        deployment_id: ${{ vars.DEPLOYMENT_ID }}
        registry: ${{ vars.REGISTRY }}
        type: private
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        dockerfile: ./Backend/Dockerfile

  build-deploy-frontend:
    runs-on: ubuntu-latest
    needs: check-changed-directory
    if: contains(needs.check-changed-directory.outputs.check-changes, 'Frontend/') || inputs.trigger-frontend == 'build'
    steps:
    - uses: actions/checkout@v4
    - name: Build Image
      uses: computesphere/build-and-deploy-image-action@v1
      with:
        mode: build-and-deploy
        name: ${{ vars.IMAGE_NAME }}/backend-mern:v.0.${{ github.run_number }}
        account_id: ${{ vars.COMPUTESPHERE_ACCOUNT_ID }}
        token: ${{ secrets.COMPUTESPHERE_API_TOKEN }}
        deployment_id: ${{ vars.FE_DEPLOYMENT_ID }}
        registry: ${{ vars.REGISTRY }}
        type: private
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        dockerfile: ./Backend/Dockerfile
        extra_build_args: |
          REACT_APP_BACKEND_URL=https://d-backend-4765b9f4.computesphere.site/api
          REACT_APP_NODE_ENV=${{ inputs.environment}} 
          REACT_APP_BACKEND_BASE_URL=localhost
          REACT_APP_BACKEND_PORT=4000


  # build_and_push_backend:
  #   uses: chukwukelu2023/automation-hub/.github/workflows/image_build_dockerhub.yaml@v1.0.0
  #   needs: check-changed-directory
  #   if: contains(needs.check-changed-directory.outputs.check-changes, 'Backend/') || inputs.trigger-backend == 'build'
  #   with:
  #     context-path: ./Backend
  #     tag-name: oluchioraekwe/backend-mern:v.${{ github.run_number }}
  #     registry-name: docker.io
  #   secrets:
  #      REGISTRY-PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
  #      REGISTRY-USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

  # build_and_push_frontend:
  #   uses: chukwukelu2023/automation-hub/.github/workflows/image_build_dockerhub.yaml@v1.0.0
  #   needs: check-changed-directory
  #   if: contains(needs.check-changed-directory.outputs.check-changes, 'Frontend/') || inputs.trigger-frontend == 'build'
  #   with:
  #     context-path: ./Frontend
  #     tag-name: oluchioraekwe/frontend-mern:v.${{ github.run_number }}
  #     registry-name: docker.io
  #     build-args: |
  #       REACT_APP_BACKEND_URL=https://d-backend-4765b9f4.computesphere.site
  #       REACT_APP_NODE_ENV=${{ inputs.environment}} 
  #       REACT_APP_BACKEND_BASE_URL=localhost
  #       REACT_APP_BACKEND_PORT=4000
  #   secrets:
  #      REGISTRY-PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
  #      REGISTRY-USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

